### ISSUE TITLE
vagrant up provisioner fails

### ISSUE THREAD

**Issue by felipecruz91** [tinkerbell/sandbox#47] opened 2021-01-27 20:50 UTC
## Expected Behaviour
Following the local setup with Vagrant, the `vagrant up provisioner` command fails.

## Current Behaviour

![image](https://user-images.githubusercontent.com/15997951/106052133-87632400-60e9-11eb-96f7-63945ef7674d.png)

## Steps to Reproduce (for bugs)

1. Run  `vagrant up provisioner` 
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
Vagrant & VirtualBox
* Link to your project or a code example to reproduce issue:
* https://docs.tinkerbell.org/setup/local-vagrant/

**Comment by gianarb** [comment] 2021-01-27 20:59
Hello

Looking at the error it looks a connectivity issue. The download of docker
failed.

Can you ssh into the box and see if you can reach internet?

Thanks

**Comment by gianarb** [comment] 2021-01-28 14:50
Hey @felipecruz91 ! This was in my backlog but I never had time to really put my heads around it. Do you mind to replace in Vagrantfile the provisioner box with this? https://app.vagrantup.com/tinkerbelloss/boxes/sandbox-ubuntu1804/versions/0.1.0

Technically it should come with all the dependencies installed, but overall, your issue looks like a network one.
So let me know if you discovered something more about it

**Comment by gianarb** [comment] 2021-02-09 10:32
I can't reproduce and now that we are using a new Vagrant image the problem as it got reported should not happen anymore.

I am closing this, for now, if you can reproduce again with the sandbox `master` branch let us know!

**Closed by gianarb** 2021-02-09 10:32 UTC
