### ISSUE TITLE
vagrant worker connection refused

### ISSUE THREAD

**Issue by stephenalandavis** [tinkerbell/sandbox#40] opened 2021-01-20 17:49 UTC
When I run `vagrant up worker` I get the following error message from Vagrant:

```bash
$ vagrant up worker
Bringing machine 'worker' up with 'virtualbox' provider...
==> worker: Importing base box 'generic/alpine38'...
==> worker: Matching MAC address for NAT networking...
==> worker: Checking if box 'generic/alpine38' version '3.1.22' is up to date...
==> worker: Setting the name of the VM: vagrant_worker_1611164269731_58978
==> worker: Fixed port collision for 22 => 2222. Now on port 2200.
==> worker: Clearing any previously set network interfaces...
==> worker: Preparing network interfaces based on configuration...
    worker: Adapter 1: nat
    worker: Adapter 2: intnet
==> worker: Forwarding ports...
    worker: 22 (guest) => 2200 (host) (adapter 1)
==> worker: Running 'pre-boot' VM customizations...
==> worker: Booting VM...
==> worker: Waiting for machine to boot. This may take a few minutes...
    worker: SSH address: 127.0.0.1:22
    worker: SSH username: vagrant
    worker: SSH auth method: private key
    worker: Warning: Connection refused. Retrying...
    worker: Warning: Connection refused. Retrying...
    worker: Warning: Connection refused. Retrying...
    worker: Warning: Connection refused. Retrying...
```

The logs (displayed from the `docker-compose logs -f tink-server boots nginx` command) show the following:

```
boots_1                  | {"level":"info","ts":1611163375.3727038,"caller":"syslog/receiver.go:114","msg":"host=192.168.1.5 facility=kern app-name=ipxe msg=\"http://192.168.1.2/misc/osie/current/vmlinuz-x86_64... Operation not permitted (http://ipxe.org/410c613c)\"","service":"github.com/tinkerbell/boots","pkg":"syslog"}
boots_1                  | {"level":"info","ts":1611163375.3755722,"caller":"syslog/receiver.go:114","msg":"host=192.168.1.5 facility=kern app-name=ipxe msg=\"Could not boot image: Operation not permitted (http://ipxe.org/410c613c)\"","service":"github.com/tinkerbell/boots","pkg":"syslog"}
boots_1                  | {"level":"info","ts":1611163375.3776581,"caller":"syslog/receiver.go:114","msg":"host=192.168.1.5 facility=kern app-name=ipxe msg=\"No more network devices\"","service":"github.com/tinkerbell/boots","pkg":"syslog"}
```
 
I then tried interrupting `vagrant up worker` with `Ctrl-C`, and ran `vagrant reload worker`, and the following error message was printed:

```bash
$ vagrant reload worker
==> worker: Checking if box 'generic/alpine38' version '3.1.22' is up to date...
==> worker: Fixed port collision for 22 => 2222. Now on port 2200.
==> worker: Clearing any previously set network interfaces...
==> worker: Preparing network interfaces based on configuration...
    worker: Adapter 1: nat
    worker: Adapter 2: intnet
==> worker: Forwarding ports...
    worker: 22 (guest) => 2200 (host) (adapter 1)
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "e7ac9167-740b-40bb-bf22-9a5e99c816e2", "--natpf1", "ssh,tcp,127.0.0.1,2200,,22"]

Stderr: VBoxManage: error: A NAT rule of this name already exists
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component NATEngineWrap, interface INATEngine, callee nsISupports
VBoxManage: error: Context: "AddRedirect(Bstr(strName).raw(), proto, Bstr(strHostIp).raw(), RTStrToUInt16(strHostPort), Bstr(strGuestIp).raw(), RTStrToUInt16(strGuestPort))" at line 1907 of file VBoxManageModifyVM.cpp
```

## Expected Behaviour

I should be prompted to login by the GUI.

## Current Behaviour

`Connection refused. Retrying...` is printed until I interrupt `vagrant up worker` with `Ctrl-C`.

## Possible Solution

Unsure :man_shrugging:

## Steps to Reproduce (for bugs)

1. Follow the steps in the **Local Setup with Vagrant** guide until you try to bring up the worker machine with `vagrant up worker` step.

## Context

I'm trying to complete the **Local Setup with Vagrant** guide. I've followed all of the steps provided in the guide, as provided. This is my second attempt at following the guide, and I am getting stuck at the same step. I'm unsure of the next steps that I should take.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

Ubuntu 20.04.1 LTS

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

Vagrant & VirtualBox

**Comment by gianarb** [comment] 2021-01-26 14:14
Hello @webdavis ! Thank you for opening this issue

I am not able to reproduce but I will keep trying with a proper Ubuntu box. @parauliya do you have Ubuntu installed? Do you mind giving it a try as well?

**Comment by webdavis** [comment] 2021-01-27 18:05
It may have worked the first time if I waited long enough. However, on my first attempt it wasn't clear to me that the `Connection refused` message is supposed to be printed. I have since watched your YouTube videos on Tinkerbell and learned that is normal behavior. I will attempt it again later today (starting from scratch), and I will let you know what I find.

**Comment by webdavis** [comment] 2021-08-30 03:12
@jacobweinstock Hey, this weekend was crazy busy and I didn't get a chance to try it out. I will attempt it asap. My apologies!

**Comment by nshalman** [comment] 2021-10-05 15:26
Hi @stephenalandavis, just checking in. Is this still a problem or did #90 resolve you issue?

**Comment by jacobweinstock** [comment] 2021-11-16 16:12
Hey @stephenalandavis, thanks again for submitting this. no rush on checking this. Whenever you have some time please test out the latest commit. I'm going to close this, but If you find this issue is still occurring with latest, please do re-open this ticket.

**Closed by jacobweinstock** 2021-11-16 16:12 UTC
Labels: kind/support
